const test=require('node:test');
const assert=require('node:assert/strict');
const {calculate,money}=require('../server-cashflow/model.js');
function sample(){return {p:100,q:10,x:30,y:32,gNode:1,upDeposit:3,upTail:5,allocation:'quantity',clients:[{name:'A',p:110,q:6,x:35,b:6,deposit:2,tail:4},{name:'B',p:112,q:4,x:35,b:4,deposit:2,tail:4}]};}
test('default guarantee-first flow reconciles sales, rebates, profit and cash',()=>{let r=calculate(sample());assert.deepEqual(r.errors,[]);assert.equal(r.events[0].isGuarantee,true);assert.equal(r.cost,1000);assert.equal(r.sales,1108);assert.equal(r.profit,98);assert.equal(r.finalCash,98);assert.equal(r.depositNet,84.3);assert.equal(r.gap,0);assert.equal(r.feasible,true);assert.equal(r.allocated,320);assert.equal(r.clients[0].g,192);assert.equal(r.clients[1].g,128);assert.equal(r.events.at(-1).realized,98);assert.equal(r.events.at(-1).cumulativeRebates,10);});
test('paying before collections flags a temporary gap despite a profitable deal',()=>{let s=sample();s.upDeposit=2;s.upTail=4;s.clients.forEach(c=>{c.deposit=3;c.tail=5;});let r=calculate(s);assert.equal(r.profit,98);assert.equal(r.gap,615.7);assert.equal(r.firstGap.node,2);assert.equal(r.firstGap.balance,-300);assert.equal(r.feasible,false);});
test('same-node payments cannot conceal upstream funding needs',()=>{let s=sample();s.upDeposit=2;let r=calculate(s);assert.equal(r.gap,300);assert.equal(r.firstGap.label,'付上游预付款');});
test('insufficient deposit considers immediate proportional rebate',()=>{let s=sample();s.clients.forEach(c=>c.x=27.1);let r=calculate(s);assert.equal(r.depositNet,-2.442);assert.equal(r.gap,2.442);assert.equal(r.firstGap.node,3);});
test('partial sales reserve guarantee and full unsold procurement cash',()=>{let s=sample();s.clients.pop();let r=calculate(s);assert.equal(r.profit,54);assert.equal(r.inventory,400);assert.equal(r.finalCash,-346);assert.equal(r.clients[0].g,192);assert.equal(r.unallocated,128);assert.equal(r.gap,346);});
test('manual guarantee allocation validates aggregate capacity',()=>{let s=sample();s.allocation='manual';s.clients[0].guarantee=200;s.clients[1].guarantee=121;assert.match(calculate(s).errors.join(),/超过上游/);s.clients[1].guarantee=120;assert.equal(calculate(s).allocated,320);});
test('over-allocation and invalid inputs suppress misleading results',()=>{let s=sample();s.clients[0].q=7;assert.match(calculate(s).errors.join(),/销售数量超过/);s=sample();s.clients[0].x=101;assert.ok(calculate(s).errors.length);s=sample();s.p=NaN;assert.ok(calculate(s).errors.length);s=sample();s.clients[0].q=1.5;assert.ok(calculate(s).errors.length);s=sample();s.clients[0].b=-1;assert.ok(calculate(s).errors.length);});
test('0% and 100% advances have no double counted collections or rebates',()=>{for(let x of [0,100]){let s=sample();s.clients.forEach(c=>c.x=x);let r=calculate(s);assert.equal(r.finalCash,98);assert.equal(r.events.at(-1).cumulativeRebates,10);assert.equal(r.events.at(-1).cumulativeIn,1108);assert.equal(r.events.at(-1).realized,98);}});
test('guarantee is noncash and payment before guarantee violates sequence',()=>{let s=sample();s.gNode=4;let r=calculate(s);assert.equal(r.gap,0);assert.equal(r.feasible,false);assert.equal(r.sequenceErrors.length,1);assert.equal(r.finalCash,98);s=sample();s.y=0;r=calculate(s);assert.equal(r.finalCash,98);assert.equal(r.guarantee,0);});
test('currency rounding reconciles fractional prices and rebates',()=>{let s=sample();s.p=100.123456;s.clients.forEach(c=>{c.p+=.123456;c.x=33.333333;c.b+=.654321;});let r=calculate(s);assert.equal(r.finalCash,money(r.profit-r.inventory));assert.equal(r.events.at(-1).cumulativeRebates,r.rebates);assert.equal(r.events.at(-1).cumulativeIn,r.sales);});
test('zero customers keep full inventory and report procurement funding need',()=>{let s=sample();s.clients=[];let r=calculate(s);assert.equal(r.inventory,1000);assert.equal(r.finalCash,-1000);assert.equal(r.gap,1000);assert.equal(r.profit,0);});
