const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Data=require('../server-cashflow/data.js');
const fixture=()=>JSON.parse(fs.readFileSync(path.join(__dirname,'../server-cashflow/template.json'),'utf8'));
test('template import and export roundtrip preserve results',()=>{let r=Data.parse(JSON.stringify(fixture()));assert.equal(r.result.profit,3200);assert.equal(r.result.feasible,false);let second=Data.parse(Data.serialize(r.state));assert.deepEqual(second.result,r.result);});
test('BOM-prefixed JSON files accepted',()=>{assert.equal(Data.parse('\uFEFF'+JSON.stringify(fixture())).result.cost,177920);});
test('units, version, missing fields, null, strings and unknown fields rejected',()=>{for(const change of [d=>d.amountUnit='CNY',d=>d.schemaVersion='1.0',d=>delete d.procurement.unitPrice,d=>d.procurement=null,d=>d.procurement.advanceRate='30',d=>d.intermediaries[0].rebatePerUnit=null,d=>d.unrecognized=0,d=>d.customers[0].surprise='x']){let d=fixture();change(d);assert.throws(()=>Data.parse(d));}});
test('reject malformed and oversized text without changing caller state',()=>{let s=fixture(),before=JSON.stringify(s);assert.throws(()=>Data.parse('{broken'));assert.throws(()=>Data.parse(' '.repeat(Data.LIMIT+1)));assert.equal(JSON.stringify(s),before);});
test('validate allocation totals and schedule ordering',()=>{let d=fixture();d.customers[0].quantity=129;assert.throws(()=>Data.parse(d),/销售数量超过/);d=fixture();d.customers[0].balanceNode=1;assert.throws(()=>Data.parse(d),/尾款节点/);});
test('valid funding-risk scenarios remain importable and carry their warning',()=>{let d=fixture();d.procurement.advanceNode=2;let r=Data.parse(d);assert.equal(r.result.gap,53376);assert.equal(r.result.feasible,false);});
test('manual mode requires explicit guarantee amounts and roundtrips',()=>{let d=fixture();d.guaranteeAllocation='manual';assert.throws(()=>Data.parse(d),/guaranteeAmount/);d.customers[0].guaranteeAmount=62272;let r=Data.parse(d);assert.deepEqual(Data.serialize(r.state),d);});
test('missing commissions are not silently replaced by zero',()=>{let d=fixture();delete d.intermediaries[0].rebatePerUnit;assert.throws(()=>Data.parse(d),/rebatePerUnit/);delete d.intermediaries;assert.throws(()=>Data.parse(d),/intermediaries/);});

test('legacy per-customer rebates cannot be silently mixed with per-unit broker fees',()=>{let d=fixture();d.customers[0].rebateTotal=6;assert.throws(()=>Data.parse(d),/未知字段/);d=fixture();d.intermediaries=[];let r=Data.parse(d);assert.equal(r.result.rebates,0);assert.equal(r.result.profit,14080);assert.deepEqual(Data.serialize(r.state),d);});
