const test=require('node:test');
const assert=require('node:assert/strict');
const {calculate,money}=require('../server-cashflow/model.js');
function sample(){return {p:100,q:10,x:30,y:32,gNode:1,upDeposit:3,upTail:5,allocation:'quantity',intermediaries:[{name:'居间 A',rate:1},{name:'居间 B',rate:0}],clients:[{name:'A',p:110,q:6,x:35,deposit:2,tail:4},{name:'B',p:112,q:4,x:35,deposit:2,tail:4}]};}
test('default guarantee-first flow reconciles sales, rebates, profit and cash',()=>{let r=calculate(sample());assert.deepEqual(r.errors,[]);assert.equal(r.events[0].isGuarantee,true);assert.equal(r.cost,1000);assert.equal(r.sales,1108);assert.equal(r.profit,98);assert.equal(r.finalCash,98);assert.equal(r.depositNet,84.3);assert.equal(r.gap,0);assert.equal(r.feasible,true);assert.equal(r.allocated,320);assert.equal(r.clients[0].g,192);assert.equal(r.clients[1].g,128);assert.equal(r.events.at(-1).realized,98);assert.equal(r.events.at(-1).cumulativeRebates,10);});
test('paying before collections flags a temporary gap despite a profitable deal',()=>{let s=sample();s.upDeposit=2;s.upTail=4;s.clients.forEach(c=>{c.deposit=3;c.tail=5;});let r=calculate(s);assert.equal(r.profit,98);assert.equal(r.gap,615.7);assert.equal(r.firstGap.node,2);assert.equal(r.firstGap.balance,-300);assert.equal(r.feasible,false);});
test('same-node payments cannot conceal upstream funding needs',()=>{let s=sample();s.upDeposit=2;let r=calculate(s);assert.equal(r.gap,300);assert.equal(r.firstGap.label,'付上游预付款');});
test('insufficient deposit considers immediate proportional rebate',()=>{let s=sample();s.clients.forEach(c=>c.x=27.1);let r=calculate(s);assert.equal(r.depositNet,-2.442);assert.equal(r.gap,2.442);assert.equal(r.firstGap.node,3);});
test('partial sales reserve guarantee and full unsold procurement cash',()=>{let s=sample();s.clients.pop();let r=calculate(s);assert.equal(r.profit,54);assert.equal(r.inventory,400);assert.equal(r.finalCash,-346);assert.equal(r.clients[0].g,192);assert.equal(r.unallocated,128);assert.equal(r.gap,346);});
test('manual guarantee allocation validates aggregate capacity',()=>{let s=sample();s.allocation='manual';s.clients[0].guarantee=200;s.clients[1].guarantee=121;assert.match(calculate(s).errors.join(),/超过上游/);s.clients[1].guarantee=120;assert.equal(calculate(s).allocated,320);});
test('over-allocation and invalid inputs suppress misleading results',()=>{let s=sample();s.clients[0].q=7;assert.match(calculate(s).errors.join(),/销售数量超过/);s=sample();s.clients[0].x=101;assert.ok(calculate(s).errors.length);s=sample();s.p=NaN;assert.ok(calculate(s).errors.length);s=sample();s.clients[0].q=1.5;assert.ok(calculate(s).errors.length);s=sample();s.intermediaries[0].rate=-1;assert.ok(calculate(s).errors.length);});
test('0% and 100% advances have no double counted collections or rebates',()=>{for(let x of [0,100]){let s=sample();s.clients.forEach(c=>c.x=x);let r=calculate(s);assert.equal(r.finalCash,98);assert.equal(r.events.at(-1).cumulativeRebates,10);assert.equal(r.events.at(-1).cumulativeIn,1108);assert.equal(r.events.at(-1).realized,98);}});
test('guarantee is noncash and payment before guarantee violates sequence',()=>{let s=sample();s.gNode=4;let r=calculate(s);assert.equal(r.gap,0);assert.equal(r.feasible,false);assert.equal(r.sequenceErrors.length,1);assert.equal(r.finalCash,98);s=sample();s.y=0;r=calculate(s);assert.equal(r.finalCash,98);assert.equal(r.guarantee,0);});
test('currency rounding reconciles fractional prices and rebates',()=>{let s=sample();s.p=100.123456;s.intermediaries[0].rate=1.654321;s.clients.forEach(c=>{c.p+=.123456;c.x=33.333333;});let r=calculate(s);assert.equal(r.finalCash,money(r.profit-r.inventory));assert.equal(r.events.at(-1).cumulativeRebates,r.rebates);assert.equal(r.events.at(-1).cumulativeIn,r.sales);});
test('zero customers keep full inventory and report procurement funding need',()=>{let s=sample();s.clients=[];let r=calculate(s);assert.equal(r.inventory,1000);assert.equal(r.finalCash,-1000);assert.equal(r.gap,1000);assert.equal(r.profit,0);});

test('independent per-unit broker fees follow each customer receipts and sold units',()=>{let s=sample();s.intermediaries=[{name:'A',rate:2},{name:'B',rate:3}];s.clients[0].x=20;s.clients[1].x=50;let r=calculate(s);assert.equal(r.rebates,50);assert.equal(r.profit,58);assert.deepEqual(r.intermediaries.map(b=>[b.total,b.deposit,b.tail]),[[20,6.4,13.6],[30,9.6,20.4]]);assert.deepEqual(r.clients.map(c=>[c.b,c.depositRebate,c.tailRebate]),[[30,6,24],[20,10,10]]);assert.equal(r.events.at(-1).cumulativeRebates,50);assert.equal(r.finalCash,58);s.clients.pop();r=calculate(s);assert.equal(r.rebates,30);assert.equal(r.intermediaries[0].total,12);});
test('broker rounding reconciles individual obligations and aggregate payments',()=>{let s=sample();s.intermediaries=[{name:'A',rate:.123456},{name:'B',rate:.654321}];s.clients[0].x=33.333333;let r=calculate(s);assert.equal(r.rebates,money(r.intermediaries.reduce((a,b)=>a+b.total,0)));assert.equal(r.events.at(-1).cumulativeRebates,r.rebates);r.intermediaries.forEach(b=>assert.equal(money(b.deposit+b.tail),b.total));});
test('zero commissions and invalid broker data are explicit',()=>{let s=sample();s.intermediaries=[];assert.equal(calculate(s).profit,108);delete s.intermediaries;assert.ok(calculate(s).errors.length);s=sample();s.intermediaries[0].rate=NaN;assert.ok(calculate(s).errors.length);});
test('guarantee allocation percentages reflect quantity and manual amounts',()=>{let s=sample();let r=calculate(s);assert.deepEqual(r.clients.map(c=>c.allocationRate),[60,40]);s.allocation='manual';s.clients[0].guarantee=160;s.clients[1].guarantee=80;r=calculate(s);assert.deepEqual(r.clients.map(c=>c.allocationRate),[50,25]);assert.equal(r.unallocated,80);s.y=0;s.clients.forEach(c=>c.guarantee=0);assert.equal(calculate(s).clients[0].allocationRate,null);});

test('actual downstream guarantee ratio uses its selling price rather than upstream cost or total guarantee',()=>{let s=sample();let r=calculate(s);assert.equal(r.clients[0].guaranteeSalesRate,192/660*100);assert.equal(r.clients[1].guaranteeSalesRate,128/448*100);s.clients[0].p=120;r=calculate(s);assert.equal(r.clients[0].g,192);assert.equal(r.clients[0].guaranteeSalesRate,192/720*100);s.allocation='manual';s.clients[0].guarantee=180;s.clients[1].guarantee=100;r=calculate(s);assert.equal(r.clients[0].guaranteeSalesRate,25);assert.equal(r.clients[1].guaranteeSalesRate,100/448*100);});
test('automatic advances follow downstream guarantee percentage minus margin',()=>{const s=sample();s.advanceMargin=3;s.clients.forEach(c=>c.advanceMode='auto');let r=calculate(s);assert.equal(r.clients[0].x,26.1);assert.equal(r.clients[1].x,25.6);s.y=40;r=calculate(s);assert.equal(r.clients[0].x,33.4);assert.equal(r.clients[1].x,32.7);s.clients[0].p=120;r=calculate(s);assert.equal(r.clients[0].x,30.3);s.advanceMargin=3.1;r=calculate(s);assert.equal(r.clients[0].x,30.2);assert.equal(s.clients[0].x,35);});
test('manual advances remain fixed and automatic rates use manual guarantee allocation',()=>{const s=sample();s.advanceMargin=3;s.allocation='manual';s.clients[0].advanceMode='auto';s.clients[0].guarantee=198;s.clients[1].guarantee=100;let r=calculate(s);assert.equal(r.clients[0].x,27);assert.equal(r.clients[1].x,35);assert.equal(r.clients[0].depositCash,178.2);assert.equal(r.clients[0].depositRebate,1.62);});
test('automatic rates are bounded and invalid margins rejected',()=>{const s=sample();s.advanceMargin=3;s.clients.forEach(c=>c.advanceMode='auto');s.y=0;let r=calculate(s);assert.equal(r.clients[0].x,0);assert.ok(r.warnings.some(x=>x.includes('0%')));s.y=1000;r=calculate(s);assert.equal(r.clients[0].x,100);s.advanceMargin=-.1;assert.ok(calculate(s).errors.length);});
